[project]
name = "cardprofiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Soufyane El Omrani", email = "elomranisoufyan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
cardprofiler = "cardprofiler:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
